### ISSUE TITLE
RSS Feed is not compatible with Micro.blog

### ISSUE THREAD

**Issue by jackbaty** [davidmerfield/Blot#1]
When parsing Blot's RSS feed, micro.blog is running into encoding issues that seem specific to Blot.

See https://micro.blog/manton/126420 for a brief discussion and this comment by the author, Manton...

> Yes, this is a known issue because of the way Blot encodes URLs in RSS feeds. I've never seen an RSS feed that encodes URLs like this before, so it will need to be worked-around in Micro.blog. Hope to get to it soon.

It's not clear to me if it's a problem on the feed's end or the way Micro.blog is parsing things, but thought I'd mention it.

**Comment by davidmerfield** [comment]
Hi @manton and @jackbaty! Sorry about this. Here's the default template used to render Blot's RSS feeds:

https://github.com/davidmerfield/Blot/blob/master/app/templates/_/feed.rss

Are you referring to the URLs in the blog posts inside the description tag, or the URLs in the link and guid properties of the feed items?

**Comment by jackbaty** [comment]
It does seem to validate, I assume it's correct. Manton has made a change to his parser which is intended to fix it, but I have not had a chance to test it yet. I'll let you know if it works as advertised. If so, I think you can close this and pretend it never happened :). Blot is pretty great, so thanks.

**Comment by manton** [comment]
I've fixed the Micro.blog side of processing Blot feeds so that it should work correctly now. Some of the URLs had "/" encoded in the Blot feeds, which was confusing Micro.blog. I think it's valid but it was just unusual encoding... I hadn't seen that in an RSS feed before. Thanks!

**Comment by davidmerfield** [comment]
Ok, great! I suspect this is due to [Mustache's default escaping](https://github.com/janl/mustache.js/issues/307)?
