### ISSUE TITLE
Error in the developer documentation

### ISSUE THREAD

**Issue by eli-oat** [davidmerfield/Blot#102]
I am not certain if this is the right place to report this, but I noticed an error in the developer docs: 

- URL: <https://blot.im/developers/reference>
- Location of error: at the very bottom of the page (see screenshot)
- Expected: I believe that the label should read "A list of all your site's tags" or something along those lines

![screen shot 2019-01-21 at 9 58 36 am](https://user-images.githubusercontent.com/3342274/51482065-6e3d7500-1d63-11e9-8817-197171bf2d1f.png)

**Comment by davidmerfield** [comment]
Definitely the right place to report this. It'll be fixed in #91. I'll leave this issue open until I merge that PR.

Thanks for letting me know

**Comment by davidmerfield** [comment]
Fixed in 36a91e1,  thank you for bringing this to my attention
