### ISSUE TITLE
Ghost importer dependencies missing

### ISSUE THREAD

**Issue by ghostlevel** [davidmerfield/Blot#13]
// I used the Ghost importer for blot.im ; i'm not super used to NPM, took me a while somehow to manage to get all the dependencies even with 'npm install' ... many were always missing, i had to fiddle a bit but i can't tell you precisely more & it may be my own fault?

!! Anyway: in the end, the import worked except it had a hardcoded domain name i had to modify when trying to download all the images from my Ghost blog.

**Comment by davidmerfield** [comment]
Have updated instructions in 0410dac for readme.txt which resolves this for others in future. Thanks for bringing this to my attention. Closing for now
