### ISSUE TITLE
Git client 413 error Entity Too Large

### ISSUE THREAD

**Issue by ghostlevel** [davidmerfield/Blot#14]
Hi, not sure this is your prefered place for this kind of errors/bugs or if you had prefered i'd send you an email.

After using the Ghost importer I initially tested to git push one of the posts to blot.im with the structure "Posts/YYYY/MM-DD-title" containing one 'post.md' + two JPGs, this worked without problem.

(I renamed all the .TXT files from the importer as .MD)

But when trying to git push all my posts (once i cleaned them up a bit) or only a random-ish selection of them i got this error:

>Counting objects: 208, done.
>Delta compression using up to 4 threads.
>Compressing objects: 100% (206/206), done.
>error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413 Request >Entity Too Large
>fatal: The remote end hung up unexpectedly 117.00 KiB/s
>Writing objects: 100% (208/208), 36.21 MiB | 5.99 MiB/s, done.
>Total 208 (delta 0), reused 0 (delta 0)
>fatal: The remote end hung up unexpectedly
>Everything up-to-date

Given that my archive/posts contains many images, i double-checked there weren't too many big ones (i remember seeing something about an error related to file sizes), i usually scale them down & better compress them to ~1024px etc to avoid full size ~5mb JPGs. So i double-checked and each image is way below <1mb generally. Most often they are ~100 to ~200kb

Same error in the end. I tried several times to git rm -r *, start again, etc

I tried the Dropbox client today and in this case there was no problem to upload everything.

I removed everything from Dropbox, gave it time for blot.im to sync. Disconnected the Dropbox client & set up the Git client/repo again in a new folder. Same error.

Could that be a similar NGINX file size limit error (given it's trying to push ~36mb at once) or something else?

(The git client for my use in this case may not be the best if the posts generally contain more images than text i guess.. ?)

**Comment by davidmerfield** [comment]
Bugs filed here are great! I believe you are correct, it is probably NGINX limiting this, specifically the [```client_max_body_size```](https://github.com/davidmerfield/Blot/blob/master/config/nginx/blot-site.conf#L5) directive in Blot's configuration.

The issue is probably that 36mb is greater than 8mb. I'm not sure what a sensible ```client_max_body_size``` value is. I believe GitHub has a 150mb push limit.

As a work-around for now, if you incrementally add, commit, then push files (never more than 8mb in a single push) I suspect it'll work. I recognize this is far from ideal though.

**Comment by zproc** [comment]
I don't know what would be a sensible value in this case either given it's not just a limit for any single 'item' uploaded (as it may be with Dropbox i'd guess?) It's seems tricky with Git indeed with anything that isn't text. 

it's only a little trouble in this case/when importing an archive of posts then yes... — It didn't occur to me i could just add everything incrementally. i only payed more attention to the error & recalled having seen something about the NGINX conf/limit when i wanted to report the problem & i tested with Dropbox to compare... (Although i didn't know what was the size limit.)

Anyway yes as a work-around it'd totally work :) Thanks.

// Hah, I wish again for a SFTP feature where i could just drag&drop without Dropbox as a 'middleman'. :) I haven't yet exactly figured out how i'll use my account but i'm happy to support the project, it's really great.

**Comment by davidmerfield** [comment]
I bumped the max size to 100mb, going to consider this resolved for now
