### ISSUE TITLE
How do I host the website on my own server?

### ISSUE THREAD

**Issue by Tekameikite** [davidmerfield/Blot#233]
Hey, I want to host the website that's generated by Blot on my own server. I wondered if it's possible to use Blot with Node.js on my local machine to "generate" the blog, whose files would be later uploaded to the hosting provider. I like the concept of layouts and markdown posts that Blot is using so I wanted to ask if it could be done like that. I think that noone has asked this question because it's a fairly easy process to do (or maybe it isn't).

**Comment by davidmerfield** [comment]
Hello! Thank you for considering Blot. Unfortunately, this isn't recommended right now, per the readme:

> I recommend waiting until I write a guide before attempting to run Blot on your own server. Eventually I will refactor the code such that Blot can be installed quickly and simply. I will write the neccessary documentation and sell Blot at a reasonable price to self-hosters, with an option to pay more for support. 

Please note that Blot isn't a true static blogging platform: there are some dynamic features, like the search engine so it's not really possible to generate a site and then upload it elsewhere

**Comment by TheAmateurTechnologist** [comment]
Hi David

Do you have any idea when this might be happening?

Scott Jordan (The Amateur Technologist)

**Comment by davidmerfield** [comment]
@TheAmateurTechnologist @Tekameikite It's a medium-term goal but I won't give you a firm timeline. The best way to find out about when self-hosting is documented is to subscribe to the newsletter: 

https://blot.im/news

As always, please let me know if you have any questions

**Comment by hyjwonder** [comment]
Hi, any news about the self-hosting feature?

**Comment by davidmerfield** [comment]
I did add a guide to setting a simple version of Blot's server here:

https://github.com/davidmerfield/Blot/blob/master/notes/_guides/_development-environment.txt

I know it's taking a while – getting self hosting sorted is not my top priority now. My approximate list of priorities:

- resolve stability issues with the syncing from Dropbox and Google Drive
- improve the template selection
- add further clients (e.g. FTP, OneDrive)
- add other payment methods (PayPal, etc.)
- then complete self-hosting

There's a public list of my tasks here:

https://blot.im/about/news

Please let me know if you have any questions about this or anything else

**Comment by hyjwonder** [comment]
Hi David,

It’s good to hear from you. I understand your priorities.

I subscribed to your hosting service (my account is ***@***.*** ***@***.***> ) for a month but I found it still miss the password protection feature. So I canceled renewal.

I am checking with some tech gurus to see if they can do the self-hosting and add password protection to it. ;-)

Have a nice day!


Yejun Huang
***@***.***
