### ISSUE TITLE
Images prefixed with an underscore show up as posts if used in a delayed post

### ISSUE THREAD

**Issue by o9simon** [davidmerfield/Blot#3]
1. Name an image _myimage.png
2. Create a post with the filename 2018-01-24-my-blog-post.md
3. Use _myimage.png in 2018-01-24-my-blog-post.md with the syntax 
```
 ![My image](_myimage.png)
```

2018-01-24 is tomorrow. Tomorrow, when the blog post becomes public _myimage.png will also be turned into a blog post.

**Comment by o9simon** [comment]
I did some more research on this and a possible cause might be how I name my images. My images are often named something following the pattern _2018-02-01-my-image.png. On February 1st this image would get turned into a post. If I rename the image to _2018-02-01-my-image-2.png, the post would disappear. If I rename it again to _2018-02-01-my-image.png, no post would be generated.

**Comment by davidmerfield** [comment]
Thank you so much for reporting this! I made an error in the logic to determine whether or not a public file should become a blog post. I have just deployed a fix. 

Please let me know if you have any questions.
