### ISSUE TITLE
Title property is being displayed twice on entry page.

### ISSUE THREAD

**Issue by jordan-miguel** [davidmerfield/Blot#302]
So I have a test post from which I only want to display the content. 

In my entry.html file I have the following markup. 

_I have only injected the `{{title}}` once within the `h1`._

`<article class="entry">

          <h1 class="entry-title">
            {{title}}
          </h1>

          {{#date}}
          <p class="entry-date">
            <small>{{date}}</small>
          </p>
          {{/date}}

          {{{body}}}

        </article>`

The issue: `{{{body}}}` is outputting the post title, as well as the content. 
I have already displayed my title in the `h1` - I do not need it to be shown again.
**Only 'The content...' should be output**

Perhaps I'm missing something really simple here, and the issue is in my folder set up via Dropbox. 

**Dropbox screenshot:**
<img width="722" alt="Screenshot 2020-05-28 at 16 49 59" src="https://user-images.githubusercontent.com/14114089/83163791-58805280-a103-11ea-8ee9-daf5aec9d1b9.png">

**Chrome screenshot:**
![Screenshot 2020-05-28 at 16 53 19](https://user-images.githubusercontent.com/14114089/83164129-c4fb5180-a103-11ea-8a01-c59bd217cadc.png)

**Comment by jordan-miguel** [comment]
Fixed: 
<img width="442" alt="Screenshot 2020-05-28 at 17 31 13" src="https://user-images.githubusercontent.com/14114089/83168220-0e9a6b00-a109-11ea-99de-560e46540928.png">
Using my HTML tags in my .txt fixed this for me.

**Comment by Pinjasaur** [comment]
I'd recommend the Markdown-style single '#' to signify a <h1>. HTML, as you
discovered, can also be used.
