### ISSUE TITLE
Template settings for an inactive custom template affect the active built-in template

### ISSUE THREAD

**Issue by freetonik** [davidmerfield/Blot#327]
Steps to reproduce the issue:

1. Fork a built-in template and install it (e.g. fork `Scrapbook`)
2. Change some setting (e.g. "Hide dates")
3. Install some built-in template (e.g. install `Diary`)

Result: setting persists (e.g. dates are still hidden).

Expected result: settings should be isolated to the custom template.

**Comment by davidmerfield** [comment]
Good spot, this happens because `hideDates` and `dateFormat` aren’t  part of the `template`’s package.json at the moment, even thought the template editor makes it seem that way, confusingly, they’re properties of `blog`. 

I will fix this!

**Comment by davidmerfield** [comment]
Should be fixed!
