### ISSUE TITLE
feature request: dark mode

### ISSUE THREAD

**Issue by flbn** [davidmerfield/Blot#532]
simple as the title, it would be cool to have a plugin for enabling dark mode!

**Comment by davidmerfield** [comment]
Hello! Thank you for the suggestion and for taking a look at Blot.

I have mixed feelings about 'dark mode' myself, and am also hesitant to add a new toggle to the templates. After deliberation I have decided to hold off adding it to the templates for everyone. Of course, anyone who wants to add it to their own template is always free to do so. You can add this yourself to your template right now:

[A Complete Guide to Dark Mode on the Web](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)

Please let me know if you have any questions about this or anything else
