### ISSUE TITLE
Kissr competitor is offline

### ISSUE THREAD

**Issue by gingerbeardman** [davidmerfield/Blot#602]
My sure where/if the code for the blot website is located. 

But the kissr competitor seems to have gone offline. 

Docs may want to be updated.

**Comment by davidmerfield** [comment]
It seems to be online at my end?

I do see they're flagged as an unsafe site by Google, now, though:

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.kissr.com%2F&hl=en

**Comment by gingerbeardman** [comment]
Interesting. From my iPhone I just get "server cannot be reached" which I guess could be my ISP or DNS blocking unsafe sites.
