### ISSUE TITLE
Incorrect importer instructions

### ISSUE THREAD

**Issue by sirshannon** [davidmerfield/Blot#98]
The [instructions for running the importer](https://github.com/davidmerfield/Blot/blob/master/app/dashboard/routes/importer/readme.txt) aren't right for squarespace and aren't clear in general. This is what worked for me:

1. Step one in the readme is correct and clear enough.
2. Install the dependencies from the root of the Blot project via `npm install`
3. Copy the xml file exported from Squarespace to the Blot/app/dashboard/routes/importer/sources/squarespace folder, renaming it to dump.xml
4. Run the import script from the Blot/app/dashboard/routes/importer/sources/squarespace folder via `node index.js dump.xml output`
5. Your blog posts in markdown are located in Blot/app/dashboard/routes/importer/sources/squarespace/output/

**Comment by davidmerfield** [comment]
Thank you for putting this together, I have updated the readmes in ```/app/dashboard/routes/importer/sources/squarespace```  and ```/app/dashboard/routes/importer```. Please don't hesitate to ask if anything else comes up
